import {
  Armchair,
  ArrowUpDown,
  Baby,
  BadgeCheck,
  BatteryCharging,
  Bike,
  Blinds,
  BriefcaseBusiness,
  Building,
  Car,
  CarFront,
  Cctv,
  ChefHat,
  Clock3,
  Cpu,
  Dog,
  Droplets,
  Dumbbell,
  Expand,
  FileBadge,
  Flame,
  GraduationCap,
  HelpCircle,
  Home,
  Hospital,
  Map,
  Milestone,
  School,
  Scroll,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Snowflake,
  SplitSquareHorizontal,
  Square,
  Store,
  ThermometerSun,
  Trees,
  Truck,
  Warehouse,
  Waves,
  Wifi,
  Wind,
} from "lucide-react";
import type { ComponentType } from "react";

const featureIconMap: Record<string, ComponentType<{ className?: string }>> = {
  wifi: Wifi,
  wind: Wind,
  armchair: Armchair,
  droplets: Droplets,
  snowflake: Snowflake,
  "thermometer-sun": ThermometerSun,
  waves: Waves,
  "arrow-up-down": ArrowUpDown,
  car: Car,
  bike: Bike,
  shield: Shield,
  trees: Trees,
  building: Building,
  scroll: Scroll,
  milestone: Milestone,
  home: Home,
  expand: Expand,
  dog: Dog,
  square: Square,
  shirt: Shirt,
  "chef-hat": ChefHat,
  blinds: Blinds,
  cpu: Cpu,
  cctv: Cctv,
  dumbbell: Dumbbell,
  baby: Baby,
  warehouse: Warehouse,
  "battery-charging": BatteryCharging,
  flame: Flame,
  "file-badge": FileBadge,
  map: Map,
  "badge-check": BadgeCheck,
  "shield-check": ShieldCheck,
  "car-front": CarFront,
  "split-square-horizontal": SplitSquareHorizontal,
  store: Store,
  school: School,
  hospital: Hospital,
  "shopping-bag": ShoppingBag,
  "waves-ladder": Waves,
  truck: Truck,
  "house-minus": Home,
  "clock-3": Clock3,
  "briefcase-business": BriefcaseBusiness,
  "graduation-cap": GraduationCap,
};

export function FeatureIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const IconComponent = featureIconMap[name] || HelpCircle;
  return <IconComponent className={className} />;
}
